[tool.poetry]
name = "goit-pyweb-hw-02"
version = "0.1.0"
description = ""
authors = ["AndreyKozachok <kozachok_andrey@ukr.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flask = "^3.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
